/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FitnessRouteImport } from './routes/fitness'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FitnessRoute = FitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/fitness': typeof FitnessRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/placement': typeof PlacementRoute
  '/projects': typeof ProjectsRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/fitness': typeof FitnessRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/placement': typeof PlacementRoute
  '/projects': typeof ProjectsRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/fitness': typeof FitnessRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/placement': typeof PlacementRoute
  '/projects': typeof ProjectsRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/fitness'
    | '/login'
    | '/nutrition'
    | '/onboarding'
    | '/placement'
    | '/projects'
    | '/recovery'
    | '/settings'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/fitness'
    | '/login'
    | '/nutrition'
    | '/onboarding'
    | '/placement'
    | '/projects'
    | '/recovery'
    | '/settings'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/fitness'
    | '/login'
    | '/nutrition'
    | '/onboarding'
    | '/placement'
    | '/projects'
    | '/recovery'
    | '/settings'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  FitnessRoute: typeof FitnessRoute
  LoginRoute: typeof LoginRoute
  NutritionRoute: typeof NutritionRoute
  OnboardingRoute: typeof OnboardingRoute
  PlacementRoute: typeof PlacementRoute
  ProjectsRoute: typeof ProjectsRoute
  RecoveryRoute: typeof RecoveryRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  FitnessRoute: FitnessRoute,
  LoginRoute: LoginRoute,
  NutritionRoute: NutritionRoute,
  OnboardingRoute: OnboardingRoute,
  PlacementRoute: PlacementRoute,
  ProjectsRoute: ProjectsRoute,
  RecoveryRoute: RecoveryRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
